/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoacaoRouteImport } from './routes/doacao'
import { Route as HemocomponentesRouteImport } from './routes/hemocomponentes'
import { Route as InfeccoesRouteImport } from './routes/infeccoes'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as OndeDoarRouteImport } from './routes/onde-doar'
import { Route as QuemPodeDoarRouteImport } from './routes/quem-pode-doar'
import { Route as TriagemRouteImport } from './routes/triagem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacaoRoute = DoacaoRouteImport.update({
  id: '/doacao',
  path: '/doacao',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocomponentesRoute = HemocomponentesRouteImport.update({
  id: '/hemocomponentes',
  path: '/hemocomponentes',
  getParentRoute: () => rootRouteImport,
} as any)
const InfeccoesRoute = InfeccoesRouteImport.update({
  id: '/infeccoes',
  path: '/infeccoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeDoarRoute = OndeDoarRouteImport.update({
  id: '/onde-doar',
  path: '/onde-doar',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemPodeDoarRoute = QuemPodeDoarRouteImport.update({
  id: '/quem-pode-doar',
  path: '/quem-pode-doar',
  getParentRoute: () => rootRouteImport,
} as any)
const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doacao': typeof DoacaoRoute
  '/hemocomponentes': typeof HemocomponentesRoute
  '/infeccoes': typeof InfeccoesRoute
  '/materiais': typeof MateriaisRoute
  '/onde-doar': typeof OndeDoarRoute
  '/quem-pode-doar': typeof QuemPodeDoarRoute
  '/triagem': typeof TriagemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doacao': typeof DoacaoRoute
  '/hemocomponentes': typeof HemocomponentesRoute
  '/infeccoes': typeof InfeccoesRoute
  '/materiais': typeof MateriaisRoute
  '/onde-doar': typeof OndeDoarRoute
  '/quem-pode-doar': typeof QuemPodeDoarRoute
  '/triagem': typeof TriagemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doacao': typeof DoacaoRoute
  '/hemocomponentes': typeof HemocomponentesRoute
  '/infeccoes': typeof InfeccoesRoute
  '/materiais': typeof MateriaisRoute
  '/onde-doar': typeof OndeDoarRoute
  '/quem-pode-doar': typeof QuemPodeDoarRoute
  '/triagem': typeof TriagemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doacao'
    | '/hemocomponentes'
    | '/infeccoes'
    | '/materiais'
    | '/onde-doar'
    | '/quem-pode-doar'
    | '/triagem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doacao'
    | '/hemocomponentes'
    | '/infeccoes'
    | '/materiais'
    | '/onde-doar'
    | '/quem-pode-doar'
    | '/triagem'
  id:
    | '__root__'
    | '/'
    | '/doacao'
    | '/hemocomponentes'
    | '/infeccoes'
    | '/materiais'
    | '/onde-doar'
    | '/quem-pode-doar'
    | '/triagem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoacaoRoute: typeof DoacaoRoute
  HemocomponentesRoute: typeof HemocomponentesRoute
  InfeccoesRoute: typeof InfeccoesRoute
  MateriaisRoute: typeof MateriaisRoute
  OndeDoarRoute: typeof OndeDoarRoute
  QuemPodeDoarRoute: typeof QuemPodeDoarRoute
  TriagemRoute: typeof TriagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacao': {
      id: '/doacao'
      path: '/doacao'
      fullPath: '/doacao'
      preLoaderRoute: typeof DoacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocomponentes': {
      id: '/hemocomponentes'
      path: '/hemocomponentes'
      fullPath: '/hemocomponentes'
      preLoaderRoute: typeof HemocomponentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infeccoes': {
      id: '/infeccoes'
      path: '/infeccoes'
      fullPath: '/infeccoes'
      preLoaderRoute: typeof InfeccoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-doar': {
      id: '/onde-doar'
      path: '/onde-doar'
      fullPath: '/onde-doar'
      preLoaderRoute: typeof OndeDoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-pode-doar': {
      id: '/quem-pode-doar'
      path: '/quem-pode-doar'
      fullPath: '/quem-pode-doar'
      preLoaderRoute: typeof QuemPodeDoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoacaoRoute: DoacaoRoute,
  HemocomponentesRoute: HemocomponentesRoute,
  InfeccoesRoute: InfeccoesRoute,
  MateriaisRoute: MateriaisRoute,
  OndeDoarRoute: OndeDoarRoute,
  QuemPodeDoarRoute: QuemPodeDoarRoute,
  TriagemRoute: TriagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
